services:
  - name: restaurant-platform-api
    type: web
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_ACCESS_TTL
        value: 15m
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_TTL
        value: 7d
      - key: COOKIE_DOMAIN
        sync: false
      - key: WEB_ORIGIN
        value: https://restaurant-platform-web-47vd.onrender.com
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SEED_ENABLED
        value: "true"

  - name: restaurant-platform-web
    type: web
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./apps/web/Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
